### ISSUE TITLE
README Zhang's method for camera calibration not accessible

### ISSUE THREAD

**Issue by jasperdoan** [max9001/NeRF-Training-in-Google-Colab#2]
## Description  
A reference link in the README file leads to a "DOI Not Found" error. The DOI cannot be resolved, and the error message suggests possible reasons such as an incorrect DOI, an incomplete or improperly formatted string, or an inactive DOI.

## Steps to Reproduce  
1. Navigate to the repository's README file.  
2. Click on the reference link associated with the DOI.  
3. Observe the error message:  
   - "This DOI cannot be found in the DOI System. Possible reasons are:  
     - The DOI is incorrect in your source. Search for the item by name, title, or other metadata using a search engine.  
     - The DOI was copied incorrectly. Check to see that the string includes all the characters before and after the slash and no sentence punctuation marks.  
     - The DOI has not been activated yet. Please try again later, and report the problem if the error continues."

## Expected Behavior  
The link should resolve to the correct resource or paper.

## Actual Behavior  
The link leads to a "DOI Not Found" error.

## Suggested Fix  
- Verify the DOI in the source.  
- Ensure the DOI string in the README includes all necessary characters and is free of formatting issues.  
- If the DOI is incorrect, update the link to the correct DOI or provide an alternative link.  
- If the DOI is inactive, consider reaching out to the publisher or source for clarification.

## Additional Information  
- **The DOI in question:** *"Approach: Follow Zhang's method for camera calibration [[1]](https://doi.org/10.1109/34.888718%7D%7B10.1109/34.888718)"*  

Let me know if you need any additional information or assistance!

-----------------------------------

![image](https://github.com/user-attachments/assets/c728d394-d983-461b-8fac-978bc77a9b34)
![image](https://github.com/user-attachments/assets/293d0085-5d25-4c6a-94ec-877834bbc23d)

**Comment by jasperdoan** [comment]
Please resolve this ASAP, it is important to me that I know where your sources come from

**Comment by max9001** [comment]
![image](https://github.com/user-attachments/assets/fad114a0-a606-41b7-85eb-40fe866b44dc)
---
what the hell look at the DOI's they match exactly 
---
![image](https://github.com/user-attachments/assets/4d52cf9b-f1f4-4b9b-92c2-4c99b9796fd9)
---
This is obviously a big issue so I advise you to reach out to the DOI support to report this issue

**Comment by jasperdoan** [comment]
I suggest you change the link that direct towards the new site.
